# Generated by Django 4.1.7 on 2023-04-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_authorized',
        ),
    ]
