# Generated by Django 4.1.7 on 2023-04-01 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='label',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='label',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
