# Generated by Django 4.1.7 on 2023-04-19 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstaff',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectstaff',
            name='user',
        ),
        migrations.AddField(
            model_name='projectstaff',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
        migrations.AddField(
            model_name='projectstaff',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
