# Generated by Django 4.1.7 on 2023-04-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_board_title_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_pinned',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
