# Generated by Django 4.1.7 on 2023-04-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_is_pinned_project_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Beklemede', 'Beklemede'), ('İnaktif', 'İnaktif'), ('Aktif', 'Aktif'), ('Tamamlandı', 'Tamamlandı')], default='Aktif', max_length=11),
        ),
    ]
