# Generated by Django 4.1.7 on 2023-04-20 16:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_invitation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=ckeditor.fields.RichTextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
