# Generated by Django 4.1.7 on 2023-04-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Beklemede', 'Beklemede'), ('İnaktif', 'İnaktif'), ('Aktif', 'Aktif'), ('Tamamlandı', 'Tamamlandı')], default='Aktif', max_length=11),
        ),
    ]
