# Generated by Django 4.1.7 on 2023-04-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
