# Generated by Django 4.1.7 on 2023-04-12 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_project_is_pinned_pinnedprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnedprojects',
            name='pinned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
